# Generated by Django 3.2 on 2021-05-08 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RT_Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ct_thickness', models.FloatField()),
                ('qa_planar_dose', models.CharField(max_length=50)),
                ('qa_point_dose', models.CharField(max_length=50)),
                ('qa_calc_check', models.CharField(max_length=50)),
            ],
        ),
    ]
