# Generated by Django 3.2 on 2021-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_consistency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rt_techniques',
            name='calc_grid',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
