# Generated by Django 3.2 on 2021-05-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan_consistency', '0002_rt_techniques_calc_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctsettings_name', models.CharField(max_length=50, verbose_name='Nome da Configuração CT')),
                ('ct_thickness', models.FloatField(verbose_name='Espessura do corte (mm)')),
                ('ct_fov', models.FloatField(blank=True, max_length=50, verbose_name='FOV')),
            ],
        ),
        migrations.CreateModel(
            name='QACalcCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_check_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('calc_check_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='QAPlanarDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planar_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('planar_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('planar_resolution', models.CharField(blank=True, max_length=30, verbose_name='Resolução')),
            ],
        ),
        migrations.CreateModel(
            name='QAPointDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('point_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('point_volume', models.CharField(blank=True, max_length=30, verbose_name='Volume Sensível')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linac_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('linac_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('linac_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
            ],
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='ct_thickness',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_calc_check',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_planar_dose',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_point_dose',
        ),
        migrations.AddField(
            model_name='rt_techniques',
            name='ct_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plan_consistency.ctsettings'),
        ),
        migrations.AddField(
            model_name='rt_techniques',
            name='treatment_machine',
            field=models.ManyToManyField(blank=True, null=True, to='plan_consistency.TreatmentMachine'),
        ),
        migrations.AddField(
            model_name='rt_techniques',
            name='qa_calc_check',
            field=models.ManyToManyField(blank=True, null=True, to='plan_consistency.QACalcCheck'),
        ),
        migrations.AddField(
            model_name='rt_techniques',
            name='qa_planar_dose',
            field=models.ManyToManyField(blank=True, null=True, to='plan_consistency.QAPlanarDose'),
        ),
        migrations.AddField(
            model_name='rt_techniques',
            name='qa_point_dose',
            field=models.ManyToManyField(blank=True, null=True, to='plan_consistency.QAPointDose'),
        ),
    ]
