# Generated by Django 3.2 on 2021-05-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_consistency', '0004_auto_20210509_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctsettings',
            name='ct_fov',
            field=models.CharField(blank=True, max_length=50, verbose_name='FOV'),
        ),
    ]
