# Generated by Django 3.2 on 2021-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_consistency', '0005_alter_ctsettings_ct_fov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rt_techniques',
            name='ct_settings',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_calc_check',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_planar_dose',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='qa_point_dose',
        ),
        migrations.RemoveField(
            model_name='rt_techniques',
            name='treatment_machine',
        ),
        migrations.DeleteModel(
            name='CTSettings',
        ),
        migrations.DeleteModel(
            name='QACalcCheck',
        ),
        migrations.DeleteModel(
            name='QAPlanarDose',
        ),
        migrations.DeleteModel(
            name='QAPointDose',
        ),
        migrations.DeleteModel(
            name='RT_Techniques',
        ),
        migrations.DeleteModel(
            name='TreatmentMachine',
        ),
    ]
