# Generated by Django 3.2 on 2021-05-09 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctsettings_name', models.CharField(max_length=50, verbose_name='Nome da Configuração CT')),
                ('ct_thickness', models.FloatField(verbose_name='Espessura do corte (mm)')),
                ('ct_fov', models.CharField(blank=True, max_length=50, verbose_name='FOV')),
            ],
        ),
        migrations.CreateModel(
            name='QACalcCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calc_check_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('calc_check_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='QAPlanarDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planar_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('planar_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('planar_resolution', models.CharField(blank=True, max_length=30, verbose_name='Resolução')),
            ],
        ),
        migrations.CreateModel(
            name='QAPointDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('point_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
                ('point_volume', models.CharField(blank=True, max_length=30, verbose_name='Volume Sensível')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linac_name', models.CharField(max_length=50, verbose_name='Nome')),
                ('linac_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('linac_manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='RT_Techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('calc_grid', models.FloatField()),
                ('ct_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.ctsettings')),
                ('qa_calc_check', models.ManyToManyField(blank=True, to='settings.QACalcCheck')),
                ('qa_planar_dose', models.ManyToManyField(blank=True, to='settings.QAPlanarDose')),
                ('qa_point_dose', models.ManyToManyField(blank=True, to='settings.QAPointDose')),
                ('treatment_machine', models.ManyToManyField(blank=True, to='settings.TreatmentMachine')),
            ],
        ),
    ]
